id: A0BCD9D20
title: An Aspiration to Travel to the Hidden Land of Pemokö
type: translation
pechas:
- I8ACCDC60
- ID21EA3AA
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:56:49.382788
  last_modified_at: 2023-01-04 12:56:49.382819
  collections:
  - Lelung Shepé Dorje Series
  - Works of Tibetan Masters
alignment_to_base:
  I8ACCDC60/5050: 335C
  ID21EA3AA/4A99: 335C
